---
version: '3.3'
services:
  python:
    container_name: bib-lite-python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    environment:
      - SQLITE_DB=/app/bib.db
    volumes:
      - ./bib.db:/app/bib.db
      - ./relaton-data-rfcs/:/app/relaton-data-rfcs/
      - ./relaton-data-ids/:/app/relaton-data-ids/
